# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/j5ltechn/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/j5ltechn

PRODUCT_COPY_FILES += \
    vendor/samsung/j5ltechn/proprietary/vendor/firmware/libpn548ad_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn548ad_fw.so

PRODUCT_PACKAGES += \
    sensors.vendor.msm8916 \
    libsec-ril-dsds \
    libsec-ril
