# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/j53gxx/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/j53gxx

PRODUCT_PACKAGES += \
    sensors.vendor.msm8916 \
    libsec-ril-dsds \
    libsec-ril
    

