# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/j5-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/j5-common

PRODUCT_COPY_FILES += \
    vendor/samsung/j5-common/proprietary/etc/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Bluetooth_cal.acdb \
    vendor/samsung/j5-common/proprietary/etc/General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/General_cal.acdb \
    vendor/samsung/j5-common/proprietary/etc/Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Global_cal.acdb \
    vendor/samsung/j5-common/proprietary/etc/Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Handset_cal.acdb \
    vendor/samsung/j5-common/proprietary/etc/Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Hdmi_cal.acdb \
    vendor/samsung/j5-common/proprietary/etc/Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Headset_cal.acdb \
    vendor/samsung/j5-common/proprietary/etc/Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Speaker_cal.acdb \
    vendor/samsung/j5-common/proprietary/etc/T13QL_s5k3l2xx_module_info.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/T13QL_s5k3l2xx_module_info.xml 
    
    
PRODUCT_PACKAGES += \
    camera.vendor.msm8916 \
    libAl_Awb \
    libAl_Awb_Sp \
    libTsAf \
    libaec_algo_front \
    libaec_algo_rear \
    libaf_algo_rear \
    libawb_algo_front_al \
    libawb_algo_rear_al \
    libchromatix_s5k3l2xx_common \
    libchromatix_s5k3l2xx_common_1080p_b \
    libchromatix_s5k3l2xx_common_1080p_s \
    libchromatix_s5k3l2xx_common_res0 \
    libchromatix_s5k3l2xx_common_res1 \
    libchromatix_s5k3l2xx_common_res2 \
    libchromatix_s5k3l2xx_common_res3 \
    libchromatix_s5k3l2xx_default_video \
    libchromatix_s5k3l2xx_golfshot \
    libchromatix_s5k3l2xx_hfr_1080p_b \
    libchromatix_s5k3l2xx_hfr_1080p_s \
    libchromatix_s5k3l2xx_hfr_120 \
    libchromatix_s5k3l2xx_liveshot \
    libchromatix_s5k3l2xx_panorama \
    libchromatix_s5k3l2xx_pip \
    libchromatix_s5k3l2xx_preview \
    libchromatix_s5k3l2xx_snapshot \
    libchromatix_s5k3l2xx_sports \
    libchromatix_s5k3l2xx_uhd_video \
    libchromatix_s5k3l2xx_zslshot \
    libmmcamera2_stats_algorithm \
    libmmcamera_cac2_lib \
    libmmcamera_wavelet_lib \
    libQSEEComAPI \
    libactuator_dw9806_camcorder \
    libactuator_dw9806_camera \
    libchromatix_s5k3l2xx_vt \
    libchromatix_s5k3l2xx_vt_hd \
    libchromatix_s5k5e3yx_wide_common \
    libchromatix_s5k5e3yx_wide_pip \
    libchromatix_s5k5e3yx_wide_preview \
    libchromatix_s5k5e3yx_wide_snapshot \
    libchromatix_s5k5e3yx_wide_video \
    libchromatix_s5k5e3yx_wide_vt \
    libchromatix_s5k5e3yx_wide_vt_hd \
    libchromatix_s5k5e3yx_wide_zslshot \
    libdiag \
    libdsutils \
    libidl \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_pproc_modules \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera2_vpe_module \
    libmmcamera2_wnr_module \
    libmmcamera_dw_dw9806b_eeprom \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hdr_lib \
    libmmcamera_image_stab \
    libmmcamera_imglib \
    libmmcamera_lsi_s5k5e3yx_eeprom \
    libmmcamera_rohm_brce064gwz_eeprom \
    libmmcamera_s5k3l2xx \
    libmmcamera_s5k5e3yx \
    libmmcamera_silicon_sr544_eeprom \
    libmmcamera_sunny_p12v01m_eeprom \
    libmmcamera_sunny_p5v23c_eeprom \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmipl \
    libmmjpeg \
    libmmqjpeg_codec \
    liboemcamera \
    libqcci_legacy \
    libqmi \
    libqmi_cci \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmiservices \
    libqomx_jpegenc \
    qseecomd
   

